---
- name: DEPLOY WAZUH
  hosts: windows
  gather_facts: no
  tasks:
    - name: Install Wazuh Agent
      win_package:
        path: https://packages.wazuh.com/4.x/windows/wazuh-agent-4.4.4-1.msi
        state: present
        arguments: >-
          WAZUH_MANAGER={{ hostvars['monitoring']['ansible_host'] }}
          WAZUH_REGISTRATION_SERVER={{ hostvars['monitoring']['ansible_host'] }}
          WAZUH_AGENT_GROUP=default

    - name: Start Wazuh
      win_service:
        name: WazuhSvc
        start_mode: auto
        state: started