all:
  vars:
    force_dns_server: yes
    dns_server: 10.LUDUSRANGENUMBER.10.254
    ansible_user: localuser
    ansible_password: password

windows:
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 400
    ansible_winrm_read_timeout_sec: 500
    two_adapters: no
    nat_adapter: Ethernet
    domain_adapter: Ethernet
  hosts:
    DC01:
      ansible_host: 10.LUDUSRANGENUMBER.10.100
      dns_domain: DC01
      dict_key: DC01
    ADCS:
      ansible_host: 10.LUDUSRANGENUMBER.10.110
      dns_domain: ADCS
      dict_key: ADCS
    FS:
      ansible_host: 10.LUDUSRANGENUMBER.10.130
      dns_domain: FS
      dict_key: FS
    WEB:
      ansible_host: 10.LUDUSRANGENUMBER.10.135
      dns_domain: WEB
      dict_key: WEB
    WS1:
      ansible_host: 10.LUDUSRANGENUMBER.10.145
      dns_domain: WS1
      dict_key: WS1
    WS2:
      ansible_host: 10.LUDUSRANGENUMBER.10.146
      dns_domain: WS2
      dict_key: WS2

ubuntu:
  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    monitoring:
      ansible_host: 10.LUDUSRANGENUMBER.10.200
      dns_domain: monitoring
      dict_key: monitoring